name: Deploy
on:
  push:
    branches:
      - 'main'
    paths:
      - 'lib/**'
      - 'icons/**'
      - 'docs/**'
      - '.github/workflows/deploy*.yml'
      - 'package.json'
jobs:
  deploy:
    if: ${{ github.repository == 'primer/octicons' }}
    name: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Vercel Action
        uses: amondnet/vercel-action@v20
        id: vercel-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN_SHARED }}
          vercel-args: '--prod'
          github-comment: false
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID_SHARED }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
